print("กรอกข้อมูลส่วนตัว")
name = str(input("โปรดกรอกชื่อ: "))
age = int(input("โปรดกรอกอายุ: "))
StuID = int(input("โปรดกรอกรหัสประจำตัวนักเรียน: "))
level = int(input("โปรดกรอกระดับชั้น: "))
nickname = str(input("โปรดกรอกชื่อเล่น: "))
height = float(input("โปรดกรอกส่วนสูง: "))
weight = float(input("โปรดกรอกน้ำหนัก: "))

print("\nชื่อ: "+name+" อายุ: "+str(age)+" ปี")
print("รหัสประจำตัวนักเรียน: "+str(ID)+" ระดับชั้น: "+str(level))
print("ชื่อเล่น: "+nickname)
print("ส่วนสูง: "+str(height)+" เซนติเมตร น้ำหนัก: "+str(weight))
print("ส่วนสูง + น้ำหนัก = "+str(height + weight))