print("กรอกข้อมูลส่วนตัว")
name = str(input("โปรดกรอกชื่อ: "))
age = int(input("โปรดกรอกอายุ: "))
StuID = int(input("โปรดกรอกรหัสประจำตัวนักเรียน: "))
level = int(input("โปรดกรอกระดับชั้น: "))
nickname = str(input("โปรดกรอกชื่อเล่น: "))
height = float(input("โปรดกรอกส่วนสูง: "))
weight = float(input("โปรดกรอกน้ำหนัก: "))

print(f"\nชื่อ: {name} อายุ: {age} ปี")
print(f"รหัสประจำตัวนักเรียน: {StuID} ระดับชั้น: {level}")
print(f"ชื่อเล่น: {nickname}")
print(f"ส่วนสูง: {height} เซนติเมตร น้ำหนัก: {weight} กิโลกรัม")
print(f"ส่วนสูง + น้ำหนัก = {height + weight}")